services:
  postgres:
    image: postgres:16
    container_name: instagram-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 160603
      POSTGRES_DB: instagram_clone
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: instagram-rabbitmq
    ports:
      - "5672:5672"     # port giao thức AMQP - dùng để code Java kết nối
      - "15672:15672"   # port giao diện quản lý qua web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  minio:
     image: minio/minio
     container_name: instagram-minio
     ports:
       - "9000:9000"
       - "9001:9001"
     environment:
       MINIO_ROOT_USER: minioadmin
       MINIO_ROOT_PASSWORD: minioadmin123
     command: server /data --console-address ":9001"
     volumes:
       - minio_data:/data

  worker:
    build:
      context: ../instagram-clone-worker
    depends_on:
      - postgres
      - minio
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/instagram_clone
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 160603

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: instagram-media
volumes:
  postgres_data:
  minio_data:

